#Backend Dockerfile

#Fetch node image and install
FROM node:20

WORKDIR /backend

COPY . .

RUN apt-get update && apt-get install -y netcat-openbsd
RUN yarn install --frozen-lockfile

# Generate Prisma client and apply migrations (After Postgres has been run)
RUN chmod +x pgsql_wait.sh

EXPOSE 8000

CMD ["bash", "./pgsql_wait.sh"]
